<a href="https://colab.research.google.com/github/baiyunming/I2DL-WS2020/blob/main/%E2%80%9CLecture_2_Basics_of_Numpy_ipynb%E2%80%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tutorial from : https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np
# from skimage.transform import resize
print(np.__version__)

1.18.5


### Why we need numpy array?

In [2]:
data_list_1 = [[1, 3, 5], [2, 4, 6]]
data_list_2 = [[-1, 0, -1], [0, -1, -0]]

# What should we do if we want to sum up values inside two lists? list append
sum_list = data_list_1 + data_list_2

# Make all as NUMPY array! convert list to array
data_array_1 = np.array(data_list_1)
data_array_2 = np.array(data_list_2)

# And sum up the numpy arrays
sum_array = data_array_1 + data_array_2

# TRY PRINT and SEE values!
print(sum_list)
print(sum_array)

[[1, 3, 5], [2, 4, 6], [-1, 0, -1], [0, -1, 0]]
[[0 3 4]
 [2 3 6]]


### Create array in a various way

In [5]:
# Try various methods to create the array!
a = np.arange(15)
# a = np.linspace(0, 14, 15)  # 15 numbers from 0 to 14
# a = np.ones((15))
# a = np.zeros((15), dtype = int)
# a = np.full((15), 10)
# a = np.random.rand(15)

print(a)
print(a.dtype)
print()

# Watch out how array is reshaped. This would be different from the MATLAB
a = a.reshape(3, 5)
print(a)
print(a.T) # transposing the array
print()

# Check the shape / dimension of the array
print(a.shape, a.ndim)

# Add the new axis
a = a[:, np.newaxis,:]
print(a.shape, a.ndim)
print(a)
print()

# make a new array looks like others.
b = np.ones_like(a)
# b = np.zeros_like(a)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
int64

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

(3, 5) 2
(3, 1, 5) 3
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]

(3, 1, 5)


In [ ]:
a = np.arange(25).reshape(-1, 5) # -1 calculates the rest dimension automatically
print(a)
print()

# Take the part of array
partial_a = a[1:4, 2:4]
print(partial_a)
print()

# another array with different shape
b = np.arange(2) * 2 - 1
print(b)
print()

## Check what happens. This is called as "broadcast"
print(partial_a + b)
print(partial_a * b)
print()

## If you are not unsure/suspecious of broadcasting... increase dimension duplication
tile_b = np.tile(b, [3, 1])
print(tile_b)
print('Shape of tiled b : ' , tile_b.shape)
print()

## And... add the tiled b and partial a
print(partial_a + tile_b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 7  8]
 [12 13]
 [17 18]]

[-1  1]

[[ 6  9]
 [11 14]
 [16 19]]
[[ -7   8]
 [-12  13]
 [-17  18]]

[[-1  1]
 [-1  1]
 [-1  1]]
Shape of tiled b :  (3, 2)

[[ 6  9]
 [11 14]
 [16 19]]


### Eye matrix and its diagonals

In [6]:
# The "I" matrix diagonal matrix
a = np.eye(10)
print(a)

# Get the diagonal of a
b = np.diag(a)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Numpy Operations


In [ ]:
a = np.random.rand(2, 3)
print(a)

print(a.sum()) # summing up all values

print(a.min()) # get the minimum value in a

print(a.max()) # get the maximum value in a

print(a.cumsum(axis=1)) # cumulative summation

[[0.27357966 0.24643089 0.68977172]
 [0.45654504 0.0739983  0.08327903]]
1.8236046258719252
0.07399829630033228
0.6897717199887647
[[0.27357966 0.52001054 1.20978226]
 [0.45654504 0.53054333 0.61382236]]


In [ ]:
# Try printing and see the results
b = np.arange(5)
print(b)
print(np.exp(b))
print(b ** 2) # np.square(b)
print(np.sqrt(b))
print()

c = np.array([-1, 0, -1, 0, -1])
print(b + c)
print(b * c)

# this is element wise multiplication!
print(np.multiply(b, c))
print()

# if you want to multiplication between matrices, use np.matmul(A, B)
d = np.array([4, 3, 2, 1, 0]).reshape(5, 1)
print(np.matmul(b, d))

[0 1 2 3 4]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[ 0  1  4  9 16]
[0.         1.         1.41421356 1.73205081 2.        ]

[-1  1  1  3  3]
[ 0  0 -2  0 -4]
[ 0  0 -2  0 -4]

[10]


### Indexing and iterating

In [ ]:
a = np.arange(16)
print(a)
print(a[1:16:4])
print('*'*100)

a = a.reshape(4, 2, 2)
print(a)
print('*'*100)

idx_list = [1, 3]
print(a[idx_list])
print('*'*100)

for slices in a:
    print(slices)
    print(slices.shape)
    print()
print('*'*100)

for element in a.flatten():
    print(element)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 1  5  9 13]
****************************************************************************************************
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
****************************************************************************************************
[[[ 4  5]
  [ 6  7]]

 [[12 13]
  [14 15]]]
****************************************************************************************************
[[0 1]
 [2 3]]
(2, 2)

[[4 5]
 [6 7]]
(2, 2)

[[ 8  9]
 [10 11]]
(2, 2)

[[12 13]
 [14 15]]
(2, 2)

****************************************************************************************************
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Stacking arrays

In [9]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.hstack((a, b)))            # horizontal stack
print(np.vstack((a, b)))            # vertical stack
print(np.concatenate([a[:, np.newaxis], b[:, np.newaxis]], axis=1)) # more general stack
print(a[:, np.newaxis])
print(a.shape)
print(a[:,np.newaxis].shape)

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1]
 [2]]
(2,)
(2, 1)


In [10]:
a = np.arange(4).reshape(2, 2)
print(a)
print()

b = np.arange(4, 8).reshape(2, 2)
print(b)
print()

print(np.hstack((a, b))) # horizontal stack
print()

print(np.vstack((a, b))) # vertical stack
print()

c = np.concatenate([a[np.newaxis, :, :], b[np.newaxis, :, :]], axis=0) # more general stack
print(c.shape)
print(c) 

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[[0 1 4 5]
 [2 3 6 7]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

(2, 2, 2)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### Watch out for the copy-by-value and copy-by-reference

In [11]:
a = np.arange(12).reshape(3, 4)
b = np.arange(12, 24).reshape(3, 4)
print(a)
print(b)

c = a               # Nothing is created.
 
print(c is a)      # They are same array! c and a are two names of same array. 'is'  for checking reference.

a[0, 0] = 200
print(c)

a[0, 0] = 0
d = a+b              # This copies value of a and b! Things change when 'operation' is performed.
print(d is a+b)     # They are not same array! Address is different.
a[0, 0] = -100     # 
print(a+b)  
print(d)                # d is not changed
print(c)                # c is changed, because it is the another 'name' of same array

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
True
[[200   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
False
[[-88  14  16  18]
 [ 20  22  24  26]
 [ 28  30  32  34]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-100    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]]


In [13]:
def f(x):
    return(id(x))
## Python function calls numpy array by reference

print(id(a))
print(f(a))
print(f(c))

139657238789216
139657238789216
139657238789216


In [14]:
def adding_one(a):
    print(id(a))
    a = a+1             #  a+1 is evaluated first, and creates a new array. and 'a' in here is the local variable!!!
    print(a)
    # a +=1             # This is done by python's special method called __iadd__, which modify the array referenced by arr in-place !!!

## Python function calls numpy array by reference
## But the operation can / cannot change the real value (depends on what you do)
## Always check these things carefully.

a = np.arange(10)
print(id(a))
print(a)

adding_one(a)
print(a)

139657238789136
[0 1 2 3 4 5 6 7 8 9]
139657238789136
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
